services:
    appventus_mangopay.mango_api:
        class: AppVentus\MangopayBundle\Helper\MangopayHelper
        arguments: ["%mangopay_client_id%", "%mangopay_client_password%", "%mangopay_base_url%", "@event_dispatcher", "%mangopay_debug%"]
